apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "10s"
      httpMethod: POST
      incrementalQuerying: false
      disableMetricsLookup: false
      customQueryParameters: ""
    version: 1
    withCredentials: false
